### ISSUE TITLE
Deadlock issue not getting resolved

### ISSUE THREAD

**Issue by abhisheksett** [happilymarrieddad/node-mysql-deadlock-retries2#1]
I have added my code like below:

```
const pool = mysql.createPool(config.db);

    const retries = 5;          // How many times will the query be retried when the ER_LOCK_DEADLOCK error occurs
    const minMillis = 100;        // The minimum amount of milliseconds that the system sleeps before retrying
    const maxMillis = 1000;      // The maximum amount of milliseconds that the system sleeps before retrying

    pool.on('connection', function(connection) {
        proxyMysqlDeadlockRetries(connection, retries, minMillis, maxMillis);
    })
```
But it is not helping. I'm still getting following error:

> Error: ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction
>     at Query.Sequence._packetToError (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
>     at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
>     at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:278:23)
>     at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:76:12)
>     at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
>     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:91:28)
>     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:502:10)
>     at Socket.emit (events.js:182:13)
>     at addChunk (_stream_readable.js:283:12)
>     at readableAddChunk (_stream_readable.js:264:11)
>     at Socket.Readable.push (_stream_readable.js:219:10)
>     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
>     --------------------
>     at Pool.query (/app/node_modules/mysql/lib/Pool.js:199:23)
>     at Object.pool.statQuery (/app/server-src/modules/database.js:81:21)
>     at Promise (/app/server-src/ops.js:154:12)
>     at new Promise (<anonymous>)
>     at insertGameGroup (/app/server-src/ops.js:151:12)
>     at async.series (/app/server-src/ops.js:497:23)
>     at /app/node_modules/async/dist/async.js:3888:9
>     at /app/node_modules/async/dist/async.js:473:16
>     at replenish (/app/node_modules/async/dist/async.js:1006:25)
>     at iterateeCallback (/app/node_modules/async/dist/async.js:995:17)
>     at /app/node_modules/async/dist/async.js:969:16
>     at /app/node_modules/async/dist/async.js:3885:13
>     at /app/node_modules/async/dist/async.js:1140:9
>     at /app/node_modules/async/dist/async.js:473:16
>     at iteratorCallback (/app/node_modules/async/dist/async.js:1064:13)
>     at /app/node_modules/async/dist/async.js:969:16

Anything I'm missing?

**Comment by ghost** [comment]
I think I have figured out the issue. For deadlock scenario, the error code I'm getting is: ER_LOCK_DEADLOCK. This error code check is not added in 'handleResponse' function. Could you please add this condition as well.

**Comment by happilymarrieddad** [comment]
hey guys I'll do it now

**Comment by happilymarrieddad** [comment]
@settabhishek @abhisheksett Fixed!
